version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: timeclock_user
      POSTGRES_PASSWORD: timeclock_password
      POSTGRES_DB: timeclock_db
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: